<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExercisesTableSeeder extends Seeder
{
    public function run(): void
    {
        $exercises = [
            ['id' => 1, 'name' => 'press plano mancuernas', 'description' => 'Press plano mancuernas.'],
            ['id' => 2, 'name' => 'press tras nuca barra', 'description' => 'Press tras nuca barra.'],
            ['id' => 3, 'name' => 'pullover polea', 'description' => 'Pullover polea.'],
            ['id' => 4, 'name' => 'remo agarre abierto', 'description' => 'Remo agarre abierto.'],
            ['id' => 5, 'name' => 'remo barra', 'description' => 'Remo barra.'],
            ['id' => 6, 'name' => 'remo mancuerna', 'description' => 'Remo mancuerna.'],
            ['id' => 7, 'name' => 'remo t', 'description' => 'Remo t.'],
            ['id' => 8, 'name' => 'sancadas barra', 'description' => 'Sancadas barra.'],
            ['id' => 9, 'name' => 'sentadilla barra abierto', 'description' => 'Sentadilla barra abierto.'],
            ['id' => 10, 'name' => 'sentadilla bulgar', 'description' => 'Sentadilla bulgar.'],
            ['id' => 11, 'name' => 'sentadilla frontal barra', 'description' => 'Sentadilla frontal barra.'],
            ['id' => 12, 'name' => 'sentadilla hack', 'description' => 'Sentadilla hack.'],
            ['id' => 13, 'name' => 'sentadilla mancuerna', 'description' => 'Sentadilla mancuerna.'],
            ['id' => 14, 'name' => 'sentadilla mancuerna2', 'description' => 'Sentadilla mancuerna2.'],
            ['id' => 15, 'name' => 'sentadillas guiadas smith', 'description' => 'Sentadillas guiadas smith.'],
            ['id' => 16, 'name' => 'trapecio barra', 'description' => 'Trapecio barra.'],
            ['id' => 17, 'name' => 'vuelos frontales', 'description' => 'Vuelos frontales.'],
            ['id' => 18, 'name' => 'vuelos laterales polea', 'description' => 'Vuelos laterales polea.'],
            ['id' => 19, 'name' => 'vuelos laterales mancuernas', 'description' => 'Vuelos laterales mancuernas.'],
            ['id' => 20, 'name' => 'vuelos posteriores mancuernas', 'description' => 'Vuelos posteriores mancuernas.'],
            ['id' => 21, 'name' => 'abdominales', 'description' => 'Abdominales.'],
            ['id' => 22, 'name' => 'abdominales polea', 'description' => 'Abdominales polea.'],
            ['id' => 23, 'name' => 'aductores', 'description' => 'Aductores.'],
            ['id' => 24, 'name' => 'bicep barra w', 'description' => 'Bicep barra w.'],
            ['id' => 25, 'name' => 'biceps barra z', 'description' => 'Biceps barra z.'],
            ['id' => 26, 'name' => 'biceps polea acostado', 'description' => 'Biceps polea acostado.'],
            ['id' => 27, 'name' => 'biceps unilateral banco', 'description' => 'Biceps unilateral banco.'],
            ['id' => 28, 'name' => 'bici', 'description' => 'Bici.'],
            ['id' => 29, 'name' => 'cardio escalador', 'description' => 'Cardio escalador.'],
            ['id' => 30, 'name' => 'cinta', 'description' => 'Cinta.'],
            ['id' => 31, 'name' => 'cruce poleas', 'description' => 'Cruce poleas.'],
            ['id' => 32, 'name' => 'cruce poleas2', 'description' => 'Cruce poleas2.'],
            ['id' => 33, 'name' => 'curl bicep polea', 'description' => 'Curl bicep polea.'],
            ['id' => 34, 'name' => 'curl biceps alternado', 'description' => 'Curl biceps alternado.'],
            ['id' => 35, 'name' => 'curl biceps barra', 'description' => 'Curl biceps barra.'],
            ['id' => 36, 'name' => 'curl de biceps concentrado mancuerna', 'description' => 'Curl de biceps concentrado mancuerna.'],
            ['id' => 37, 'name' => 'curl martillo', 'description' => 'Curl martillo.'],
            ['id' => 38, 'name' => 'curl sentado mancuerna', 'description' => 'Curl sentado mancuerna.'],
            ['id' => 39, 'name' => 'deltoide polea jalon a la cara', 'description' => 'Deltoide polea jalon a la cara.'],
            ['id' => 40, 'name' => 'deltoides polea', 'description' => 'Deltoides polea.'],
            ['id' => 41, 'name' => 'dominadas', 'description' => 'Dominadas.'],
            ['id' => 42, 'name' => 'dorsales en maquina', 'description' => 'Dorsales en maquina.'],
            ['id' => 43, 'name' => 'elevacion piernas colgado', 'description' => 'Elevacion piernas colgado.'],
            ['id' => 44, 'name' => 'extension triceps maquina', 'description' => 'Extension triceps maquina.'],
            ['id' => 45, 'name' => 'extension cuadriceps', 'description' => 'Extension cuadriceps.'],
            ['id' => 46, 'name' => 'extension triceps barra polea', 'description' => 'Extension triceps barra polea.'],
            ['id' => 47, 'name' => 'extension triceps mancuernas', 'description' => 'Extension triceps mancuernas.'],
            ['id' => 48, 'name' => 'extension triceps polea', 'description' => 'Extension triceps polea.'],
            ['id' => 49, 'name' => 'femoral maquina acostado', 'description' => 'Femoral maquina acostado.'],
            ['id' => 50, 'name' => 'flexion de brazos banco', 'description' => 'Flexion de brazos banco.'],
            ['id' => 51, 'name' => 'flexiones', 'description' => 'Flexiones.'],
            ['id' => 52, 'name' => 'flys en banco mancuernas', 'description' => 'Flys en banco mancuernas.'],
            ['id' => 53, 'name' => 'fondo maquina', 'description' => 'Fondo maquina.'],
            ['id' => 54, 'name' => 'fondos', 'description' => 'Fondos.'],
            ['id' => 55, 'name' => 'fondos con peso', 'description' => 'Fondos con peso.'],
            ['id' => 56, 'name' => 'gemelos haka', 'description' => 'Gemelos haka.'],
            ['id' => 57, 'name' => 'gemelos parado', 'description' => 'Gemelos parado.'],
            ['id' => 58, 'name' => 'gemelos pie', 'description' => 'Gemelos pie.'],
            ['id' => 59, 'name' => 'gemelos prensa', 'description' => 'Gemelos prensa.'],
            ['id' => 60, 'name' => 'gemelos sentado', 'description' => 'Gemelos sentado.'],
            ['id' => 61, 'name' => 'gluteo femoral', 'description' => 'Gluteo femoral.'],
            ['id' => 62, 'name' => 'gluteo maquina', 'description' => 'Gluteo maquina.'],
            ['id' => 63, 'name' => 'gluteo maquina2', 'description' => 'Gluteo maquina2.'],
            ['id' => 64, 'name' => 'gluteos polea', 'description' => 'Gluteos polea.'],
            ['id' => 65, 'name' => 'gluteos polea patadas', 'description' => 'Gluteos polea patadas.'],
            ['id' => 66, 'name' => 'jalon a la cara', 'description' => 'Jalon a la cara.'],
            ['id' => 67, 'name' => 'jalon al pecho agarre neutro', 'description' => 'Jalon al pecho agarre neutro.'],
            ['id' => 68, 'name' => 'jalon al pecho garre supino', 'description' => 'Jalon al pecho garre supino.'],
            ['id' => 69, 'name' => 'jalon dorsal jalon al pecho polea', 'description' => 'Jalon dorsal jalon al pecho polea.'],
            ['id' => 70, 'name' => 'parado femoral', 'description' => 'Parado femoral.'],
            ['id' => 71, 'name' => 'pat burro triceps', 'description' => 'Pat burro triceps.'],
            ['id' => 72, 'name' => 'pecho press maquina', 'description' => 'Pecho press maquina.'],
            ['id' => 73, 'name' => 'peck deck pecho', 'description' => 'Peck deck pecho.'],
            ['id' => 74, 'name' => 'pesmuerto', 'description' => 'Pesmuerto.'],
            ['id' => 75, 'name' => 'peso muerto barra hexagonal', 'description' => 'Peso muerto barra hexagonal.'],
            ['id' => 76, 'name' => 'peso muerto rumano', 'description' => 'Peso muerto rumano.'],
            ['id' => 77, 'name' => 'peso muerto smith', 'description' => 'Peso muerto smith.'],
            ['id' => 78, 'name' => 'press mancuernas declinado', 'description' => 'Press mancuernas declinado.'],
            ['id' => 79, 'name' => 'press mancuernas plano', 'description' => 'Press mancuernas plano.'],
            ['id' => 80, 'name' => 'press frances barra', 'description' => 'Press frances barra.'],
            ['id' => 81, 'name' => 'press frances barra cerrado', 'description' => 'Press frances barra cerrado.'],
            ['id' => 82, 'name' => 'press frances mancuernas', 'description' => 'Press frances mancuernas.'],
            ['id' => 83, 'name' => 'press inclinado', 'description' => 'Press inclinado.'],
            ['id' => 84, 'name' => 'prensa 45grados', 'description' => 'Prensa 45grados.'],
            ['id' => 85, 'name' => 'prensa horizontal', 'description' => 'Prensa horizontal.'],
            ['id' => 86, 'name' => 'prensa horizontal una pierna', 'description' => 'Prensa horizontal una pierna.'],
            ['id' => 87, 'name' => 'prensa pie', 'description' => 'Prensa pie.'],
            ['id' => 88, 'name' => 'press banco declinado', 'description' => 'Press banco declinado.'],
            ['id' => 89, 'name' => 'press militar mancuernas', 'description' => 'Press militar mancuernas.'],
            ['id' => 90, 'name' => 'press militar barra', 'description' => 'Press militar barra.']
        ];

        DB::table('exercises')->insert($exercises);
    }
}
